## Задача №4: Степенной метод

Ваша задача – реализовать степенной метод вычисления собственных значений и собственных векторов и протестировать его на синтетических данных. Подробности можно найти на [Википедии](https://ru.wikipedia.org/wiki/Степенной_метод).

Пожалуйста, обратите внимание, что предложенный метод должен быть применим также для вычисления наименьшего собственного значения (по абсолютной величине).

На всякий случай, для собственного значения $\lambda$ и собственного вектора $\boldsymbol{x}$ матрицы $\mathbf{A}$ справедливо следующее уравнение:
$$
\mathbf{A}\boldsymbol{x} = \lambda \boldsymbol{x}
$$

In [1]:
import numpy as np

In [108]:
def get_dominant_eigenvalue_and_eigenvector(data, num_steps):
    """
    data: np.ndarray – symmetric diagonalizable real-valued matrix
    num_steps: int – number of power method steps

    Returns:
    eigenvalue: float – dominant eigenvalue estimation after `num_steps` steps
    eigenvector: np.ndarray – corresponding eigenvector estimation
    """
    ### YOUR CODE HERE
    length = data.shape[1]
    # находим максимальный собственный вектор и максимальное собственное значение
    eigenvector_max = np.ones(length)
    for i in range(num_steps):
        eigenvector_max = data.dot(eigenvector_max)
        eigenvector_max /= np.sqrt(np.sum(eigenvector_max ** 2))
    eigenvalue_max = np.sqrt(np.sum(data.dot(eigenvector_max) ** 2)) / np.sqrt(np.sum(eigenvector_max ** 2))
    
    return float(eigenvalue_max), eigenvector_max

Для вашего удобства реализовано несколько тестов ниже. В качестве корректного примера используется функция из numpy.

In [99]:
def get_eigenvalues_and_eigenvectors_with_numpy(data):
    _eigenvalues, _eigenvectors = np.linalg.eig(data)
    print(_eigenvalues)
    print(_eigenvectors)
    max_index = np.argmax(np.abs(_eigenvalues))
    min_index = np.argmin(np.abs(_eigenvalues))

    _test_pair_a = np.array([_eigenvalues[max_index], _eigenvalues[min_index]])
    _test_pair_b = np.array([_eigenvectors[:, max_index], _eigenvectors[:, min_index]])
    if _test_pair_b[0][0] < 0:
        _test_pair_b[0] *= -1
    if _test_pair_b[1][0] < 0:
        _test_pair_b[1] *= -1

    return _test_pair_a, _test_pair_b

In [109]:
for _ in range(1000):
    size = np.random.choice(np.arange(2, 5))
    data = np.random.randn(size, size)
    data = data.T.dot(data)
    a0, b0 = get_dominant_eigenvalue_and_eigenvector(data, 1000)
    assert (
        type(a0) == float
    ), "Return type for eigenvalue is not Python float (please, note, numpy.float64 is a different type)"
    assert type(b0) == np.ndarray, "Return type for eigenvector is not np.ndarray"

    a1, b1 = get_dominant_eigenvalue_and_eigenvector(np.linalg.inv(data), 1000)
    a1 = 1 / a1

    if b0[0] < 0:
        b0 *= -1
    if b1[0] < 0:
        b1 *= -1

    assert np.allclose(
        data.dot(b0), a0 * b0, atol=1e-3
    ), f"Ax != \lambda x for the dominant eigenvalue check the solution!\n{data.dot(b0), a0 * b0}"
    assert np.allclose(
        data.dot(b1), a1 * b1, atol=1e-3
    ), f"Ax != \lambda x for the smallest eigenvalue check the solution!\n{data.dot(b1), a1 * b1}"

    _test_pair_a, _test_pair_b = get_eigenvalues_and_eigenvectors_with_numpy(data)

    assert np.allclose(
        _test_pair_a, np.array([a0, a1]), atol=1e-3
    ), f"Eigenvalues are different from np.linalg.eig!\n{_test_pair_a, np.array([a0, a1])}"
    assert np.allclose(
        _test_pair_b, np.array([b0, b1]), atol=1e-3
    ), f"Eigenvectors are different from np.linalg.eig!\n{_test_pair_b, np.array([b0, b1])}"

print(
    "Seems fine! Copy function `get_dominant_eigenvalue_and_eigenvector` to the .py file and submit your solution to the contest!"
)

[0.03522364 1.12540449]
[[-0.99815325  0.06074611]
 [-0.06074611 -0.99815325]]
[0.77065207 4.76331793 3.13451995]
[[-0.8873325   0.44296617  0.12814842]
 [ 0.36582055  0.50701444  0.78045608]
 [-0.28074253 -0.73940336  0.61193651]]
[5.77918108 0.72687797]
[[ 0.9519222  -0.30633988]
 [ 0.30633988  0.9519222 ]]
[4.69254254 0.03985709 1.15275351]
[[-0.88355626  0.44451332  0.14743214]
 [ 0.46310219  0.87616387  0.13369085]
 [ 0.06974735 -0.18639954  0.97999516]]
[2.3175486  0.0937335  0.28912864]
[[ 0.19958375 -0.97114385  0.13056012]
 [-0.54079814  0.00194219  0.84115016]
 [ 0.81713138  0.23848658  0.52480516]]
[10.61927686  3.8667903   1.06257838  0.0738136 ]
[[ 0.04473    -0.61199901  0.70598305 -0.35361615]
 [-0.58558171 -0.56939604 -0.54756274 -0.18181655]
 [-0.8093322   0.37386475  0.43633856  0.12171768]
 [ 0.0086414  -0.40183394  0.10663793  0.90944113]]
[13.63119642  3.28277286  1.36297035  0.09992331]
[[ 0.47963791  0.70288918 -0.50063926  0.15891697]
 [ 0.82544467 -0.37277202  

[0.45161149 5.54857219]
[[-0.99970814  0.02415858]
 [-0.02415858 -0.99970814]]
[9.49934619 8.31771815 0.66496784 0.17760454]
[[ 0.72275513 -0.27269601  0.56335053  0.29308375]
 [-0.06796548  0.3021542   0.61202915 -0.72767016]
 [ 0.51560105  0.8042892  -0.29275947  0.03957694]
 [-0.45514973  0.43296491  0.47153832  0.61889557]]
[2.25788491e+00 1.57950883e-03]
[[ 0.97986042 -0.19968362]
 [ 0.19968362  0.97986042]]
[0.02338    0.79950202]
[[-0.95687214 -0.29050938]
 [ 0.29050938 -0.95687214]]
[9.27070053 0.07219768 1.66282094 5.04103763]
[[-0.84671908 -0.19914215 -0.47859522  0.11981575]
 [-0.23798408  0.87144315  0.15822963  0.39863995]
 [ 0.38990427  0.31943737 -0.85437355 -0.12641304]
 [ 0.27277287 -0.31446624 -0.12631638  0.90041664]]
[8.62674337 4.27166251 0.95821113 0.53576576]
[[ 0.45772898 -0.78098539 -0.32383717  0.27509177]
 [-0.26334665 -0.25170763  0.72808001  0.58068177]
 [-0.15812085 -0.51314962  0.37004333 -0.7581182 ]
 [ 0.83434437  0.25175891  0.47759494 -0.11131036]]
[3

[1.86735516 1.2281678 ]
[[ 0.72590759 -0.68779225]
 [ 0.68779225  0.72590759]]
[1.9356652  3.49250475]
[[-0.86879671 -0.49516894]
 [ 0.49516894 -0.86879671]]
[9.6756295  2.73853059 0.13009277 0.74638428]
[[ 0.25421833  0.20915255  0.78154662 -0.52991804]
 [ 0.61361526 -0.28335047  0.32480992  0.66157943]
 [-0.62830195 -0.63524016  0.43891369  0.09519121]
 [-0.40507531  0.68734101  0.30172531  0.5219561 ]]
[11.19077556  3.9946703   1.43604136  0.04928534]
[[ 0.33736622 -0.52933651  0.72136745  0.29260193]
 [-0.92531387 -0.33291435  0.18048984  0.01963908]
 [-0.01913651 -0.13918194 -0.45074731  0.88152654]
 [ 0.17208157 -0.76785369 -0.49384135 -0.37001267]]
[8.41892492e+00 1.77991867e-03]
[[ 0.99854312  0.05395951]
 [-0.05395951  0.99854312]]
[4.68499415 2.00821629 0.23172673]
[[-0.33451658  0.77728252 -0.53285133]
 [ 0.78717656  0.5413357   0.29548048]
 [-0.51812326  0.32060496  0.79294435]]
[0.41360837 1.94479302]
[[-0.72312971 -0.69071226]
 [ 0.69071226 -0.72312971]]
[10.07566697  0.4

[0.01162977 3.82368684 2.48321207]
[[ 0.43960633 -0.81443037  0.37874722]
 [-0.74025197 -0.56733984 -0.36076658]
 [-0.50869764  0.1217731   0.85228987]]
[7.94628143 3.09472686 0.01057145 0.58013532]
[[ 0.02607934  0.805987   -0.5712073  -0.15305897]
 [ 0.46741882  0.4614122   0.52819834  0.53816813]
 [ 0.88238746 -0.28118161 -0.29268009 -0.23804965]
 [-0.04724287 -0.24170362 -0.55593803  0.793902  ]]
[22.35843944  0.03301711  2.02183302  4.20353012]
[[ 0.29968353  0.40742988  0.85228552  0.13341686]
 [ 0.23542047 -0.18711769  0.15400574 -0.94119414]
 [ 0.6961951   0.52195909 -0.49271287 -0.01025273]
 [ 0.60834149 -0.72563528  0.08441352  0.31023929]]
[21.1616042   3.86440435  0.2218624   0.89553701]
[[ 0.50460759  0.25881001 -0.61017125 -0.55324462]
 [ 0.42652377  0.49542985 -0.11524466  0.74789398]
 [-0.65748951  0.73326961 -0.11605965 -0.12865995]
 [-0.36215493 -0.38714638 -0.77520312  0.34354273]]
[1.04024820e+01 1.69018648e-03 4.09870463e+00]
[[-0.79239298  0.50889855  0.33635639]


[8.74982308 0.01107033 1.25902161 2.37243515]
[[ 0.84639405 -0.21590438  0.45753029 -0.16633833]
 [-0.13825137  0.78998137  0.52483915 -0.28523648]
 [ 0.44076913  0.52980094 -0.33104982  0.644546  ]
 [-0.26500235 -0.22051233  0.63687982  0.6895884 ]]
[11.80955452  3.0008599   0.18018584]
[[-0.95959178 -0.21140322 -0.18572099]
 [-0.07723123  0.8325136  -0.54859498]
 [-0.27059     0.51208377  0.81520014]]
[5.61957999 1.76417313 0.13151268]
[[ 0.11986491  0.99246625 -0.02536036]
 [ 0.14727167 -0.04303701 -0.98815933]
 [ 0.98180622 -0.11471077  0.15132079]]
[1.39482075 0.58725168]
[[ 0.94431628 -0.32903915]
 [ 0.32903915  0.94431628]]
[4.37176686 1.46217246 0.06419547]
[[ 0.12777004  0.98382252  0.12557093]
 [ 0.93157875 -0.0755988  -0.35559226]
 [ 0.34034666 -0.16241325  0.92616742]]
[3.49812952 0.32504506 0.17117441]
[[-0.09706384  0.75835295 -0.64457693]
 [ 0.80481166 -0.32121057 -0.49910116]
 [ 0.58553976  0.5672077   0.57915336]]
[0.31852725 5.36340336 9.63556108]
[[ 0.6875572   0.645

[0.47814038 5.52712687]
[[-0.97716673  0.21247395]
 [-0.21247395 -0.97716673]]
[5.70863894 2.06754465 0.11007271]
[[ 0.43202333 -0.88234903  0.18659055]
 [-0.73028415 -0.46366247 -0.50169929]
 [-0.52918892 -0.08048167  0.84467851]]
[9.42812446 7.34009828 0.05137122 0.5399731 ]
[[ 0.53541262 -0.54872173  0.48204061 -0.4241163 ]
 [ 0.23898262  0.40594095  0.68530377  0.55538995]
 [ 0.29805481 -0.55155188 -0.34380407  0.69910844]
 [-0.75324894 -0.47948611  0.42402165  0.1513762 ]]
[9.26135555 0.27226048 1.20649613 3.16382514]
[[ 4.43477166e-01 -4.77701242e-01 -7.47211365e-01 -1.29632954e-01]
 [-7.51875077e-01  2.48688886e-01 -5.65112014e-01 -2.31270659e-01]
 [ 2.93896850e-04 -2.03561897e-01  2.92417588e-01 -9.34373813e-01]
 [ 4.87864515e-01  8.17629449e-01 -1.91873766e-01 -2.38022600e-01]]
[0.58836465 4.62502077]
[[-0.78257197  0.62256013]
 [-0.62256013 -0.78257197]]
[8.67129558 1.0947502  0.48694376]
[[-0.81019107  0.49275074  0.31746989]
 [ 0.35288216 -0.02244321  0.93539857]
 [-0.46804

[1.41880829e+01 1.24893941e-03 9.40383682e-01 4.45887967e+00]
[[ 0.45812334 -0.33147071  0.8219215  -0.06852165]
 [-0.79330854 -0.30661121  0.35116739  0.39157704]
 [ 0.14275976 -0.88727103 -0.43842604 -0.01234438]
 [ 0.37470549  0.09416402 -0.09438809  0.91750739]]
[7.10721933 0.64980233 2.7019657 ]
[[ 0.97577162  0.1790771  -0.1257026 ]
 [ 0.21828639 -0.83582787  0.50372892]
 [ 0.01485942  0.51896355  0.8546672 ]]
[0.01024455 1.55408841 5.67260042]
[[-0.90226645 -0.42068727 -0.09453822]
 [-0.40758909  0.76062225  0.50529688]
 [ 0.14066409 -0.49444517  0.85775147]]
[5.19010657 0.21492604]
[[ 0.86187312 -0.50712398]
 [ 0.50712398  0.86187312]]
[9.89170267 2.57750832 0.01151739 0.20379785]
[[ 0.30609598 -0.64754488  0.63245586  0.29494146]
 [-0.25729757 -0.3694251  -0.57305635  0.68478425]
 [ 0.02298001  0.65953504  0.35547061  0.66191094]
 [ 0.91628332  0.09604298 -0.38111239  0.07716195]]
[0.11553546 0.57265808 3.59054959 4.21985484]
[[-0.47058521  0.57556942 -0.66214233 -0.09400496]


[7.79916503 3.27021219 1.09341308 0.3605562 ]
[[-0.60243716 -0.21757476  0.76791376 -0.00625685]
 [-0.58654989  0.02910979 -0.44640632  0.67515423]
 [-0.16344376 -0.84456207 -0.37037075 -0.35046619]
 [ 0.516057   -0.48839405  0.27176342  0.64907708]]
[9.87163695e+00 1.55556044e+00 7.76141205e-03]
[[ 0.1297808   0.97645092 -0.17233848]
 [ 0.6575218  -0.21484799 -0.72215333]
 [ 0.74217385  0.01959467  0.66992091]]
[0.11777321 3.62959633 9.34745315]
[[-0.8632114   0.47686507  0.16572801]
 [ 0.48143554  0.87636883 -0.01405335]
 [ 0.15194042 -0.06765634  0.98607136]]
[4.90383619 0.51588353 1.1415679 ]
[[ 0.19962202 -0.97129097 -0.12940211]
 [-0.43933697  0.02932337 -0.89784362]
 [-0.8758619  -0.23608049  0.42087044]]
[5.5782242  0.09114145 1.05477818 0.69517892]
[[-0.67470534 -0.68312553 -0.27371143  0.05651782]
 [-0.58366427  0.3267841   0.68349779  0.29219674]
 [-0.37582706  0.35178198 -0.12663439 -0.84791933]
 [-0.25072443  0.55027366 -0.66473796  0.43870219]]
[14.49537169  0.37336797  5

[0.44342287 2.99843483]
[[-0.79341922 -0.60867557]
 [ 0.60867557 -0.79341922]]
[8.4223085  0.03259227 0.73899563]
[[-0.45418485  0.77199032 -0.44468761]
 [ 0.79716077  0.12927224 -0.58976554]
 [ 0.39780752  0.62235009  0.67411389]]
[9.73875863 2.41132815 0.57628448 0.02942731]
[[-0.64763447  0.76019285  0.04508894 -0.02536568]
 [ 0.02431831  0.06852391 -0.95937196 -0.27261425]
 [-0.49648755 -0.38355874 -0.24958388  0.73762504]
 [ 0.57747583  0.51989807 -0.12361355  0.61720933]]
[0.81184193 6.64137354]
[[-0.86036197 -0.50968351]
 [ 0.50968351 -0.86036197]]
[0.00446073 1.19087415]
[[-0.99991594 -0.01296607]
 [ 0.01296607 -0.99991594]]
[18.11814169  0.39309598  5.12277053]
[[ 0.47541534  0.8795058   0.02120838]
 [ 0.87343553 -0.47474542  0.10829206]
 [-0.10531208  0.03295955  0.99389287]]
[5.81574433 3.42788276 0.82990131]
[[ 0.19684077  0.97410793  0.11120906]
 [ 0.54816802 -0.20338758  0.81126156]
 [-0.81287486  0.0987281   0.57400978]]
[0.59830324 0.02732662]
[[ 0.96842999 -0.24928567]

[8.3843351  0.02621946 1.6290394  4.6620296 ]
[[ 0.60646313  0.66716564 -0.37687844  0.21226191]
 [-0.04997266  0.11858698  0.58181409  0.80307673]
 [ 0.30013915 -0.68716785 -0.47286301  0.46272823]
 [-0.73458948  0.26196847 -0.54392608  0.30966956]]
[10.03867949  0.73045016  2.98470354  2.3661388 ]
[[ 0.19965731  0.7962076  -0.38533275 -0.42155555]
 [ 0.07771974 -0.47238681 -0.87626918 -0.05443041]
 [ 0.68173956  0.16809857 -0.07414143  0.70815047]
 [-0.69951968  0.33859567 -0.27959622  0.56378289]]
[15.01895473  7.78779787  0.139881    0.53456709]
[[-0.17998825 -0.84191863 -0.48688592 -0.14737488]
 [-0.52428424  0.11256322 -0.24529417  0.80764245]
 [-0.21511715  0.52709486 -0.70280938 -0.42656137]
 [ 0.80402418  0.02595295 -0.45698124  0.37952564]]
[1.90921935 0.02152667]
[[ 0.77264899 -0.63483347]
 [ 0.63483347  0.77264899]]
[18.98473582  4.1287289   0.64523548  0.28483995]
[[ 0.0136265  -0.64908719 -0.65700768 -0.38319845]
 [ 0.8410414   0.04808368 -0.2935859   0.45182368]
 [ 0.539

[0.64783755 3.55287212 5.54372096]
[[ 0.70565703 -0.50447584 -0.49754626]
 [-0.70275263 -0.5879704  -0.40053658]
 [ 0.09048145 -0.63229339  0.76942717]]
[0.43905399 1.25169319]
[[-0.88640411  0.46291224]
 [-0.46291224 -0.88640411]]
[0.39219829 2.93912249 6.44241881]
[[-0.69715069  0.71279715  0.07681885]
 [ 0.50505671  0.56434655 -0.6530166 ]
 [ 0.50882083  0.4164531   0.75343758]]
[11.98937277  0.67510304  4.04222371]
[[ 0.49199629 -0.86742635 -0.07423728]
 [-0.83914137 -0.49520704  0.22497055]
 [ 0.23190821  0.04838911  0.97153336]]
[0.82720914 6.27352641]
[[-0.75964949  0.65033272]
 [-0.65033272 -0.75964949]]
[3.59799613 0.69965203]
[[ 0.99376765 -0.11147134]
 [ 0.11147134  0.99376765]]
[10.12622573  5.11425159  2.69246927  1.53557704]
[[-0.86285503  0.19902617 -0.46461001  0.00270466]
 [ 0.37296639  0.85704159 -0.32468238  0.14476578]
 [ 0.34113897 -0.43428198 -0.8204454  -0.14796184]
 [-0.0012097  -0.19304779 -0.07475453  0.97833678]]
[0.00498842 2.06646115]
[[-0.95896676 -0.28351

[6.24164021 0.69073041 0.60379967]
[[-0.28119869 -0.87260938  0.39934967]
 [-0.95865161  0.23645477 -0.15835478]
 [-0.04375374  0.42736636  0.90301916]]
[3.27646591e+00 5.11569341e-02 1.27729360e-04]
[[-0.59274483  0.68246752  0.42765834]
 [ 0.08886758  0.58317452 -0.80747138]
 [ 0.80047244  0.44061952  0.40632292]]
[8.64215206 0.1449949  1.18851025]
[[ 0.48607083  0.82263415 -0.29497155]
 [ 0.63899755 -0.10429758  0.76210508]
 [-0.59616884  0.55892314  0.57635722]]
[0.07519246 1.97488935 5.07652204]
[[-0.77748548 -0.60169115 -0.18298659]
 [ 0.21530081 -0.52803299  0.82147838]
 [ 0.59089922 -0.59929035 -0.54008257]]
[1.83643242 0.85279519]
[[ 0.99837104  0.05705488]
 [-0.05705488  0.99837104]]
[0.06618881 4.20907034 6.29592217]
[[ 0.74286279  0.55824556 -0.36948176]
 [ 0.65816107 -0.50812586  0.55554668]
 [-0.12238823  0.65587347  0.74488329]]
[13.92921386  1.18125692  0.13440842  0.42139548]
[[-0.25308248 -0.15769539  0.86336037  0.40705073]
 [-0.19925396  0.93279476  0.21217588 -0.21

[8.65744158 0.40967251]
[[ 0.97925192  0.20264666]
 [-0.20264666  0.97925192]]
[10.04987496  2.87013623  0.34378603]
[[ 0.09658677 -0.99053474  0.09752914]
 [ 0.09204886  0.10645682  0.99004745]
 [ 0.99105903  0.08664804 -0.10145991]]
[12.39457054  0.62800419  0.17989615]
[[ 0.90348076  0.41929152  0.08897835]
 [ 0.24210659 -0.32790324 -0.91316147]
 [ 0.35370457 -0.84656606  0.39776751]]
[0.03262965 3.81488254]
[[-0.97104373 -0.23890183]
 [ 0.23890183 -0.97104373]]
[1.83407304 4.56384791 6.00116805]
[[-0.85623517 -0.4896877   0.16452142]
 [-0.20101543  0.02245433 -0.97933069]
 [-0.47587197  0.87160872  0.11766097]]
[0.71900151 2.18326943]
[[-0.75188277  0.65929683]
 [-0.65929683 -0.75188277]]
[9.62116057 1.73563361 0.70490683 0.11500453]
[[ 0.28004034 -0.22902173 -0.90962818  0.2042132 ]
 [-0.93791869 -0.12738935 -0.28890829 -0.14357048]
 [ 0.07662477 -0.96025488  0.23713185 -0.12572864]
 [-0.18977509 -0.09608102  0.18132032  0.96014415]]
[8.48301682 0.52590128 1.44051281]
[[-0.1743073

[9.08234951 2.55833797 0.05413686]
[[-0.84461439  0.47828007 -0.24057164]
 [ 0.47650929  0.87642179  0.06945321]
 [-0.24406031  0.05597344  0.96814335]]
[5.54318062 2.37784304 0.03072989 0.77642833]
[[ 0.55071063  0.7920727   0.24244636  0.10275403]
 [-0.23217942  0.42983215 -0.61421298 -0.61974145]
 [ 0.42729309 -0.31558332  0.38112537 -0.75668437]
 [ 0.67840337 -0.29710659 -0.64707467  0.18108261]]
[1.57142683 6.71699231]
[[-0.96890299  0.2474409 ]
 [-0.2474409  -0.96890299]]
[17.85588778  2.91515336  0.06256512  0.52924967]
[[ 0.72622164 -0.33243952  0.45445815 -0.3944032 ]
 [-0.05772777  0.82866683  0.51515304 -0.21117795]
 [ 0.06895513 -0.11319894  0.53251223  0.83597961]
 [-0.68155324 -0.43586838  0.49448544 -0.31778621]]
[1.90653112 0.02278959]
[[ 0.76688773  0.64178127]
 [-0.64178127  0.76688773]]
[0.78789741 5.57882982 4.44200672]
[[ 0.80794809 -0.52536216  0.26686041]
 [-0.50427987 -0.85074781 -0.14808771]
 [-0.30483059  0.01492515  0.95228964]]
[1.7615306  0.11506461]
[[ 0.8

[8.51011056e+00 3.95080202e-03 5.09532105e-01]
[[-0.30851382  0.72779043  0.61248699]
 [ 0.94377132  0.1537776   0.29265705]
 [-0.11880622 -0.6683364   0.73431025]]
[11.2090057   1.08917115  0.13528868]
[[ 0.26675348  0.95818487  0.10355837]
 [ 0.65304358 -0.25872849  0.71175393]
 [-0.70878535  0.12223471  0.6947532 ]]
[0.06575408 0.40386606 2.07057779 2.50333537]
[[-0.45025881  0.80467255 -0.32248504  0.21394508]
 [ 0.87479778  0.47555724  0.02446367  0.08930663]
 [-0.17249161  0.23915846  0.94238871  0.15796646]
 [ 0.04735494 -0.26296508 -0.0854895   0.95984292]]
[10.07275213  3.19381645]
[[ 0.85346681  0.52114719]
 [-0.52114719  0.85346681]]
[8.65632964 4.61844964 0.42658034 0.11023867]
[[-0.02578528 -0.12969342  0.98570144  0.10443848]
 [-0.11185951  0.41427636 -0.04400679  0.90217845]
 [-0.63852408 -0.71713621 -0.13685588  0.2434607 ]
 [ 0.76099249 -0.54522506 -0.08790069  0.3404314 ]]
[5.97899106 0.1081436 ]
[[ 0.97049522  0.24112034]
 [-0.24112034  0.97049522]]
[13.54519407  1.6

[6.34310075 0.77195186 0.04897639]
[[ 0.59057889 -0.80697888 -0.0012912 ]
 [-0.7869171  -0.57554085 -0.22251789]
 [-0.1788241  -0.13243044  0.97492775]]
[6.62709827 0.24079706 2.42690216]
[[-0.26105534  0.76651203  0.58677885]
 [ 0.25657225  0.64108855 -0.72330917]
 [ 0.93060238  0.03827255  0.36402531]]
[1.02555104 5.87526977]
[[-0.99952093  0.03095004]
 [-0.03095004 -0.99952093]]
[3.1772069  1.45562242 0.37542299]
[[ 0.48843553  0.87183607 -0.03650477]
 [ 0.76594781 -0.40832027  0.49658686]
 [-0.4180367   0.27051142  0.86721906]]
[4.13221136 0.00625137]
[[ 0.96035722 -0.27877234]
 [ 0.27877234  0.96035722]]
[8.27981266 0.03355039 1.71397384]
[[ 0.63932645  0.75702086  0.13483731]
 [ 0.42036231 -0.19725935 -0.88565472]
 [ 0.64386118 -0.62290301  0.44433616]]
[0.47063915 2.69733761]
[[-0.96633487 -0.25728761]
 [ 0.25728761 -0.96633487]]
[0.05747386 0.61731344]
[[-0.84696576 -0.53164744]
 [ 0.53164744 -0.84696576]]
[12.57567885  0.14920401  0.35883839]
[[-0.89987953  0.42546641 -0.09589

[4.62482724e+00 1.41696100e+00 9.21874401e-04]
[[ 0.26350332  0.93979003  0.21762513]
 [-0.32360155  0.29864124 -0.89782818]
 [ 0.90876181 -0.16615688 -0.38281047]]
[9.93216247 1.01851918 1.46830838 0.02398833]
[[ 0.33592399  0.93542007 -0.11017587  0.00237429]
 [ 0.06167116 -0.11545547 -0.77899628  0.61321407]
 [-0.64041301  0.2738219   0.38525429  0.60536921]
 [ 0.687912   -0.19152256  0.48229161  0.5074357 ]]
[4.24341312e-05 5.76007376e+00]
[[-0.80802563 -0.58914734]
 [ 0.58914734 -0.80802563]]
[9.14657464 3.21406132 0.01180344 0.83312984]
[[-0.43088499 -0.84060736  0.32461307 -0.04841228]
 [-0.37300458  0.01413663 -0.32915338  0.86736716]
 [ 0.7272018  -0.2339048   0.43117194  0.48016336]
 [-0.38260065  0.48833182  0.7748388   0.12154674]]
[9.3625836  0.98027442 2.87335575]
[[-0.48360624  0.79065478 -0.37548637]
 [ 0.16301257 -0.34012385 -0.92614398]
 [ 0.85997204  0.50909801 -0.03559935]]
[0.29290094 2.03986237 5.22277793]
[[-0.76686924  0.6393896   0.05561035]
 [ 0.56633684  0.63

[6.54722320e+00 3.30658865e+00 3.36459442e-03 8.76043975e-01]
[[ 0.3428816  -0.86511759 -0.24654932 -0.27058676]
 [-0.78659272 -0.42500128 -0.08526247  0.43974551]
 [ 0.51331066 -0.08065903  0.06163572  0.85217799]
 [ 0.01470608  0.25384954 -0.96340271  0.08484904]]
[16.67502285  2.52075214  0.31376177  0.1054959 ]
[[ 0.486601   -0.82581365 -0.26384304  0.10788017]
 [-0.08779939  0.11034642 -0.76449656 -0.62901506]
 [-0.15986318 -0.36802267  0.56099706 -0.72407553]
 [-0.85437375 -0.41281327 -0.17667529  0.26156556]]
[0.15444886 6.90028299]
[[-0.77616578  0.63052889]
 [-0.63052889 -0.77616578]]
[12.66605091  4.80993697  0.15799354  1.0623982 ]
[[ 0.66505668  0.40935423  0.46505259  0.416959  ]
 [-0.17388232  0.89746577 -0.27114897 -0.30132768]
 [ 0.649013   -0.12623358 -0.74604343 -0.07916067]
 [-0.32595502  0.10511605 -0.39194838  0.85386206]]
[7.46691199 1.49956177 0.08325376]
[[-0.33761102  0.85033847 -0.40366234]
 [ 0.70695113 -0.05407837 -0.70519191]
 [ 0.62148121  0.52345011  0.58

[11.03641938  0.02947701  3.38070558]
[[-0.72071826  0.66708197  0.18859171]
 [ 0.06869285  0.33943293 -0.93811864]
 [ 0.68981626  0.66316433  0.29045927]]
[8.15220409 1.33757427 0.43377557]
[[-2.77388434e-01  9.60757840e-01 -1.70901178e-04]
 [ 8.57517971e-01  2.47661397e-01  4.50917688e-01]
 [-4.33265030e-01 -1.24932800e-01  8.92565521e-01]]
[6.56312143e+00 2.42254320e+00 1.79509662e+00 1.15139167e-04]
[[ 0.51090096 -0.58633508  0.62198741  0.09123066]
 [-0.49047603  0.40167523  0.76319383  0.12500179]
 [-0.54149821 -0.54687917 -0.16136014  0.61779103]
 [ 0.45298251  0.44248316 -0.06804217  0.77096417]]
[ 0.87859114 12.45789258]
[[-0.98175981  0.19012541]
 [-0.19012541 -0.98175981]]
[6.54080027e-05 1.04221494e+00]
[[-0.99984804  0.01743268]
 [-0.01743268 -0.99984804]]
[0.90473956 1.50256265]
[[-0.89072056  0.4545513 ]
 [-0.4545513  -0.89072056]]
[7.32612188e+00 9.27692633e-04]
[[ 0.71003373 -0.70416767]
 [ 0.70416767  0.71003373]]
[13.82818519  5.38124193  1.39830503  0.28481028]
[[ 0